import = ["/Users/jason.hang/.config/alacritty/custom-themes//builtin_pastel_dark.toml"]

[font]
size = 13.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 0
y = 0

[window]
opacity = 0.85
