-- local mini_surround_ok, mini_surround = pcall(require, "mini.surround")
--
-- if not mini_surround_ok then
--   print("mini.surround not installed!")
--   return
-- end
--
-- mini_surround.setup({
--   mappings = {
--     add = "gsa",            -- Add surrounding in Normal and Visual modes
--     delete = "gsd",         -- Delete surrounding
--     find = "gsf",           -- Find surrounding (to the right)
--     find_left = "gsF",      -- Find surrounding (to the left)
--     highlight = "gsh",      -- Highlight surrounding
--     replace = "gsr",        -- Replace surrounding
--     update_n_lines = "gsn", -- Update `n_lines`
--   },
-- })
