-- local avante_ok, avante = pcall(require, 'avante')
--
-- if not (avante_ok) then
--   print('avante not installed!')
--   return
-- end
--
-- avante.setup {
--   provider = 'copilot',
--
--   auto_suggestions_provider = 'copilot',
-- }
