-- vim.keymap.set('n', '<leader>cp', '<Cmd>Copilot<CR>', { desc = '[C]opilot - [P]anel' })
-- vim.keymap.set('n', '<leader>cd', '<Cmd>Copilot disable<CR>', { desc = '[C]opilot - [D]isable' })
-- vim.keymap.set('n', '<leader>ce', '<Cmd>Copilot enable<CR>', { desc = '[C]opilot - [E]nable' })
