# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"

# spaceship theme overrides
# SPACESHIP_PROMPT_SYMBOL="$"
SPACESHIP_DOCKER_SHOW=false
# SPACESHIP_NODE_SHOW=true
SPACESHIP_TIME_SHOW=true

# plugins=(git osx gem node npm ruby bower kubectl pip postgres redis-cli tmux vagrant wd yarn zsh-syntax-highlighting)
plugins=(git osx gem node npm ruby bower kubectl pip postgres redis-cli vagrant wd yarn zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# user configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# postgres
# export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

# heroku
# export PATH="/usr/local/heroku/bin:$PATH"

# node
export PATH="$HOME/.node/bin:$PATH"

# rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init - zsh)"

# ananconda
# export PATH="$HOME/opt/anaconda3/bin:$PATH"  # commented out by conda initialize

# pyenv
# eval "$(pyenv init -)"

# docker
# eval "$(docker-machine env)"

# octave
export PATH="/usr/local/opt/texinfo/bin:$PATH"

# go lang
# export PATH="/usr/local/go/bin:$PATH"
# export PATH="$HOME/go/bin:$PATH"

# default editor
export EDITOR='nvim'

# Sourcing other files
source $HOME/.dotfiles/zsh/aliases

if [ -t 0 ]; then
  stty start ''
  stty stop ''
  stty -ixon
  stty ixoff
  stty ixany
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jdhang/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jdhang/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jdhang/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jdhang/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship
