# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# spaceship
source /opt/homebrew/opt/spaceship/spaceship.zsh

ZSH_THEME="robbyrussell"

# spaceship theme overrides
# SPACESHIP_PROMPT_SYMBOL="$"
# SPACESHIP_CONDA_SHOW=true
# SPACESHIP_DOCKER_SHOW=false
# SPACESHIP_NODE_SHOW=true
# SPACESHIP_TIME_SHOW=true

# plugins=(git osx gem node npm ruby bower kubectl pip postgres redis-cli tmux vagrant wd yarn zsh-syntax-highlighting)
plugins=(git node npm yarn)

source $ZSH/oh-my-zsh.sh

# user configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# homebrew
export PATH=$PATH:"/opt/homebrew/bin"

# postgres
# export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

# heroku
# export PATH="/usr/local/heroku/bin:$PATH"

# node
# export PATH="$HOME/.node/bin:$PATH"

# rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init - zsh)"

# anaconda
# export PATH="$HOME/opt/anaconda3/bin:$PATH"  # commented out by conda initialize

# pyenv
# eval "$(pyenv init -)"

# python
# export PATH="$HOME/Library/Python/3.8/bin:$PATH"

# docker
# eval "$(docker-machine env)"

# octave
# export PATH="/usr/local/opt/texinfo/bin:$PATH"

# go lang
# export PATH="/usr/local/go/bin:$PATH"
# export PATH="$HOME/go/bin:$PATH"

# default editor
export EDITOR='nvim'

# Sourcing other files
source $HOME/.dotfiles/zsh/aliases

if [ -t 0 ]; then
  stty start ''
  stty stop ''
  stty -ixon
  stty ixoff
  stty ixany
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jdhang/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jdhang/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jdhang/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jdhang/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

